<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = "stylesheet" href = "css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>Musculatrix</title>
</head>

<body>
    <!--MAIN HEADER-->
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="main">MUSCULATRIX</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <?php if (!isset($_SESSION['CLIENTE_ID'])) : ?>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="login">Login</a>
                            </li>
                            <!--Apartado para admin-->
                        <?php elseif ($_SESSION['CLIENTE_ID']==1) : ?> 
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="admin">Admin</a>
                            </li>
                            <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="desloguear">Logout</a>
                            </li>
                        <?php else : ?>
                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="desloguear">Logout</a>
                                </li>
                        <?php endif ?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!--INICIO MAIN CONTAINER-->
    <main class="container mt-3">