<?php require_once './src/templates/layout/header.phtml'; ?>

<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="crear/cliente">
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" required class="form-control" id="email" name="email" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" required class="form-control" id="nombre" name="nombre">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>
    
        <button type="submit" class="btn btn-primary mt-3">Crear</button>
    </form>
</div>

<?php require_once './src/templates/layout/footer.phtml'; ?>