<?php require_once './src/templates/layout/header.phtml'; ?>

<h1>Detalle de: <?= $ejercicio->nombre_ejercicio?> </h1>
<ul>
    <h3>Musculo implicado en el ejercicio</h3>
    <li>
        <?= $ejercicio->musculo_implicado ?>
    </li>
    <h3>Descripcion</h3>
    <li>
        <?= $ejercicio->descripcion ?>
    </li>
    <h3>Numero de series:</h3>
    <li>
        <?= $ejercicio->series ?>
    </li>
    <h3>Numero de repeticiones:</h3>
    <li>
        <?= $ejercicio->repeticiones ?>
    </li>
    
    Clientes que realizan este ejercicio:
    <?php foreach ($clientes as $cliente): ?>
        <?php if($ejercicio->cliente_id == $cliente->id):?>
            <li>
                <?= $cliente->nombre ?>
            </li>
        <?php endif;?>
    <?php endforeach; ?>
</ul>