<?php require './src/templates/layout/header.phtml'?>

<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="editar/ejercicio/<?= $id ?>">
        <div class="form-group">
            <label for="text">Nombre ejercicio</label>
            <input type="text" class="form-control" id="nombre" name="nombre" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="musculo">Musculo</label>
            <input type="text" class="form-control" id="musculo" name="musculo" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="descripcion">Descripcion</label>
            <input type="text" class="form-control" id="descripcion" name="descripcion">
        </div>
        <div class="form-group">
            <label for="series">Series</label>
            <input type="number" class="form-control" id="series" name="series">
        </div>
        <div class="form-group">
            <label for="repeticiones">Repeticiones</label>
            <input type="number" class="form-control" id="repeticiones" name="repeticiones">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>
    
        <button type="submit" class="btn btn-primary mt-3">Cambiar</button>
    </form>
</div>