<?php require './src/templates/layout/header.phtml'?>

<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="editar/cliente/<?= $id ?>">
        <div class="form-group">
            <label for="text">Nombre</label>
            <input type="text" class="form-control" id="nombre" name="nombre" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>
    
        <button type="submit" class="btn btn-primary mt-3">Cambiar</button>
    </form>
</div>