<?php require_once './src/templates/layout/header.phtml' ?>

<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="login">
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" required class="form-control" id="email" name="email" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" required class="form-control" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>
    
        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
    <div>
        <p>No estas registrado? Crea una cuenta haciendo <a href="registrar">click aqui</a></p>
    </div>
</div>

<?php require_once './src/templates/layout/footer.phtml' ?>